/**
 * Canadian provinces, territories and cities used for programmatic SEO pages.
 * Population figures are approximate (Statistics Canada, 2021 Census, rounded).
 */
export type Province = {
  slug: string;
  name: string;
  code: string;
  type: "province" | "territory";
  capital: string;
  largestCity: string;
  population: string;
  region: string;
  economy: string;
  industries: string[];
  bilingual?: boolean;
  lat: number;
  lng: number;
};

export type City = {
  slug: string;
  name: string;
  province: string; // province slug
  population: string;
  descriptor: string; // short phrase used in copy
  industries: string[];
  areas: string[]; // neighbourhoods / nearby communities
  fact: string; // one distinctive local fact for copy
  lat: number;
  lng: number;
  major?: boolean;
};

export const provinces: Province[] = [
  { slug: "ontario", name: "Ontario", code: "ON", type: "province", capital: "Toronto", largestCity: "Toronto", population: "14.2 million", region: "Central Canada", economy: "Canada's largest provincial economy, home to the country's financial capital, its largest tech cluster and a deep manufacturing base along the 401 corridor.", industries: ["Financial services", "Technology", "Manufacturing", "Healthcare", "Construction", "Professional services", "Education"], lat: 51.2538, lng: -85.3232 },
  { slug: "quebec", name: "Quebec", code: "QC", type: "province", capital: "Quebec City", largestCity: "Montreal", population: "8.5 million", region: "Central Canada", economy: "A bilingual, culturally distinct market with strengths in aerospace, AI, video games, hydro-electric energy and a vibrant consumer sector.", industries: ["Aerospace", "Artificial intelligence", "Manufacturing", "Tourism", "Energy", "Retail", "Creative industries"], bilingual: true, lat: 52.9399, lng: -73.5491 },
  { slug: "british-columbia", name: "British Columbia", code: "BC", type: "province", capital: "Victoria", largestCity: "Vancouver", population: "5.0 million", region: "West Coast", economy: "A Pacific gateway economy built on technology, film, real estate, tourism, forestry and trade with Asia.", industries: ["Technology", "Film and media", "Real estate", "Tourism", "Natural resources", "Construction", "Health and wellness"], lat: 53.7267, lng: -127.6476 },
  { slug: "alberta", name: "Alberta", code: "AB", type: "province", capital: "Edmonton", largestCity: "Calgary", population: "4.3 million", region: "Prairies", economy: "An entrepreneurial, high-income province diversifying from energy into technology, agriculture, logistics and professional services.", industries: ["Energy", "Technology", "Agriculture", "Construction", "Logistics", "Professional services", "Healthcare"], lat: 53.9333, lng: -116.5765 },
  { slug: "manitoba", name: "Manitoba", code: "MB", type: "province", capital: "Winnipeg", largestCity: "Winnipeg", population: "1.3 million", region: "Prairies", economy: "A diversified economy anchored by Winnipeg's manufacturing, transportation, agriculture and financial sectors.", industries: ["Manufacturing", "Agriculture", "Transportation", "Financial services", "Aerospace", "Healthcare"], lat: 53.7609, lng: -98.8139 },
  { slug: "saskatchewan", name: "Saskatchewan", code: "SK", type: "province", capital: "Regina", largestCity: "Saskatoon", population: "1.1 million", region: "Prairies", economy: "A resource and agriculture powerhouse with fast-growing tech and mining sectors in Saskatoon and Regina.", industries: ["Agriculture", "Mining", "Energy", "Technology", "Construction", "Manufacturing"], lat: 52.9399, lng: -106.4509 },
  { slug: "nova-scotia", name: "Nova Scotia", code: "NS", type: "province", capital: "Halifax", largestCity: "Halifax", population: "970,000", region: "Atlantic Canada", economy: "Atlantic Canada's economic hub with strengths in ocean technology, defence, finance, healthcare and tourism.", industries: ["Ocean technology", "Defence", "Financial services", "Tourism", "Healthcare", "Education"], lat: 44.682, lng: -63.7443 },
  { slug: "new-brunswick", name: "New Brunswick", code: "NB", type: "province", capital: "Fredericton", largestCity: "Moncton", population: "775,000", region: "Atlantic Canada", economy: "Canada's only officially bilingual province, known for cybersecurity, customer-contact centres, forestry and logistics.", industries: ["Cybersecurity", "Logistics", "Forestry", "Customer service", "Healthcare", "Manufacturing"], bilingual: true, lat: 46.5653, lng: -66.4619 },
  { slug: "newfoundland-and-labrador", name: "Newfoundland and Labrador", code: "NL", type: "province", capital: "St. John's", largestCity: "St. John's", population: "510,000", region: "Atlantic Canada", economy: "An ocean and energy economy with a growing technology sector centred on St. John's.", industries: ["Offshore energy", "Fisheries", "Technology", "Tourism", "Healthcare", "Mining"], lat: 53.1355, lng: -57.6604 },
  { slug: "prince-edward-island", name: "Prince Edward Island", code: "PE", type: "province", capital: "Charlottetown", largestCity: "Charlottetown", population: "155,000", region: "Atlantic Canada", economy: "A close-knit island economy built on agriculture, tourism, bioscience and a growing small-business community.", industries: ["Agriculture", "Tourism", "Bioscience", "Fisheries", "Retail", "Construction"], lat: 46.5107, lng: -63.4168 },
  { slug: "northwest-territories", name: "Northwest Territories", code: "NT", type: "territory", capital: "Yellowknife", largestCity: "Yellowknife", population: "41,000", region: "Northern Canada", economy: "A resource-driven northern economy with mining, government and tourism at its core.", industries: ["Mining", "Government", "Tourism", "Construction", "Transportation"], lat: 64.8255, lng: -124.8457 },
  { slug: "yukon", name: "Yukon", code: "YT", type: "territory", capital: "Whitehorse", largestCity: "Whitehorse", population: "40,000", region: "Northern Canada", economy: "A growing northern economy driven by mining, tourism, government and a strong small-business culture in Whitehorse.", industries: ["Mining", "Tourism", "Government", "Construction", "Retail"], lat: 64.2823, lng: -135.0 },
  { slug: "nunavut", name: "Nunavut", code: "NU", type: "territory", capital: "Iqaluit", largestCity: "Iqaluit", population: "37,000", region: "Northern Canada", economy: "Canada's youngest territory, with an economy centred on government, mining, fisheries and Inuit-owned enterprise.", industries: ["Government", "Mining", "Fisheries", "Arts and culture", "Transportation"], lat: 70.2998, lng: -83.1076 },
];

export const cities: City[] = [
  // Ontario
  { slug: "toronto", name: "Toronto", province: "ontario", population: "2.8 million", descriptor: "Canada's largest city and financial capital", industries: ["Finance", "Technology", "Real estate", "Healthcare", "Media", "Professional services"], areas: ["Downtown", "North York", "Scarborough", "Etobicoke", "Liberty Village", "Yorkville", "The Junction", "Leslieville"], fact: "home to the Toronto Stock Exchange and one of North America's largest tech talent pools", lat: 43.6532, lng: -79.3832, major: true },
  { slug: "ottawa", name: "Ottawa", province: "ontario", population: "1.0 million", descriptor: "Canada's capital and a major technology hub", industries: ["Government", "Technology", "Defence", "Healthcare", "Education", "Tourism"], areas: ["Kanata", "Orleans", "Barrhaven", "The Glebe", "ByWard Market", "Nepean", "Westboro"], fact: "home to Kanata North, Canada's largest technology park", lat: 45.4215, lng: -75.6972, major: true },
  { slug: "mississauga", name: "Mississauga", province: "ontario", population: "718,000", descriptor: "a corporate and logistics powerhouse beside Pearson Airport", industries: ["Logistics", "Pharmaceuticals", "Finance", "Manufacturing", "Technology", "Retail"], areas: ["Port Credit", "Streetsville", "Square One", "Meadowvale", "Erin Mills", "Cooksville"], fact: "headquarters to more than 60 Fortune 500 Canadian offices", lat: 43.589, lng: -79.6441, major: true },
  { slug: "brampton", name: "Brampton", province: "ontario", population: "656,000", descriptor: "one of Canada's fastest-growing and youngest cities", industries: ["Logistics", "Manufacturing", "Food processing", "Retail", "Healthcare", "Construction"], areas: ["Downtown Brampton", "Bramalea", "Mount Pleasant", "Springdale", "Heart Lake"], fact: "a national hub for advanced manufacturing and transportation", lat: 43.7315, lng: -79.7624 },
  { slug: "hamilton", name: "Hamilton", province: "ontario", population: "570,000", descriptor: "a reinvented industrial city with a booming creative scene", industries: ["Manufacturing", "Healthcare", "Education", "Construction", "Agri-food", "Arts"], areas: ["Downtown Hamilton", "Westdale", "Stoney Creek", "Ancaster", "Dundas", "Waterdown"], fact: "home to McMaster University and one of Canada's largest health-sciences clusters", lat: 43.2557, lng: -79.8711 },
  { slug: "london", name: "London", province: "ontario", population: "422,000", descriptor: "Southwestern Ontario's regional centre for healthcare and education", industries: ["Healthcare", "Education", "Insurance", "Manufacturing", "Technology", "Agri-food"], areas: ["Downtown London", "Byron", "Masonville", "Old East Village", "Westmount", "Oakridge"], fact: "home to Western University and a fast-growing digital creative sector", lat: 42.9849, lng: -81.2453 },
  { slug: "markham", name: "Markham", province: "ontario", population: "339,000", descriptor: "Canada's high-tech capital in York Region", industries: ["Technology", "Life sciences", "Finance", "Professional services", "Retail"], areas: ["Unionville", "Markham Village", "Cornell", "Milliken", "Thornhill"], fact: "home to more than 1,500 technology and life-science companies", lat: 43.8561, lng: -79.337 },
  { slug: "vaughan", name: "Vaughan", province: "ontario", population: "323,000", descriptor: "a rapidly urbanizing city north of Toronto", industries: ["Construction", "Manufacturing", "Logistics", "Retail", "Professional services"], areas: ["Woodbridge", "Maple", "Thornhill", "Kleinburg", "Vaughan Metropolitan Centre"], fact: "one of Canada's largest concentrations of construction and building-trades companies", lat: 43.8372, lng: -79.5083 },
  { slug: "kitchener", name: "Kitchener", province: "ontario", population: "257,000", descriptor: "the heart of Waterloo Region's technology corridor", industries: ["Technology", "Manufacturing", "Insurance", "Education", "Healthcare"], areas: ["Downtown Kitchener", "Innovation District", "Doon", "Stanley Park", "Forest Heights"], fact: "part of the Toronto-Waterloo tech corridor, North America's second-largest", lat: 43.4516, lng: -80.4925 },
  { slug: "windsor", name: "Windsor", province: "ontario", population: "230,000", descriptor: "Canada's automotive capital on the Detroit border", industries: ["Automotive", "Manufacturing", "Healthcare", "Education", "Logistics", "Agriculture"], areas: ["Downtown Windsor", "Walkerville", "South Windsor", "Riverside", "Tecumseh"], fact: "home to the busiest commercial border crossing in North America", lat: 42.3149, lng: -83.0364 },
  { slug: "richmond-hill", name: "Richmond Hill", province: "ontario", population: "202,000", descriptor: "an affluent, fast-growing community in York Region", industries: ["Technology", "Professional services", "Healthcare", "Retail", "Real estate"], areas: ["Oak Ridges", "Bayview Hill", "Mill Pond", "Langstaff", "Jefferson"], fact: "one of Canada's most highly educated and diverse communities", lat: 43.8828, lng: -79.4403 },
  { slug: "oakville", name: "Oakville", province: "ontario", population: "213,000", descriptor: "an affluent lakeside town between Toronto and Hamilton", industries: ["Automotive", "Professional services", "Finance", "Healthcare", "Retail"], areas: ["Downtown Oakville", "Bronte", "Glen Abbey", "Kerr Village", "Joshua Creek"], fact: "home to Ford Canada's headquarters and Canada's largest concentration of luxury retail outside Toronto", lat: 43.4675, lng: -79.6877 },
  { slug: "burlington", name: "Burlington", province: "ontario", population: "186,000", descriptor: "a thriving Halton community on Lake Ontario", industries: ["Manufacturing", "Professional services", "Healthcare", "Retail", "Food processing"], areas: ["Downtown Burlington", "Aldershot", "Millcroft", "Alton Village", "Tyandaga"], fact: "consistently ranked among Canada's best mid-sized cities to live in", lat: 43.3255, lng: -79.799 },
  { slug: "oshawa", name: "Oshawa", province: "ontario", population: "175,000", descriptor: "Durham Region's economic centre", industries: ["Automotive", "Healthcare", "Education", "Construction", "Retail"], areas: ["Downtown Oshawa", "Northglen", "Windfields", "Lakeview", "Kedron"], fact: "home to Ontario Tech University and a re-energized GM manufacturing hub", lat: 43.8971, lng: -78.8658 },
  { slug: "barrie", name: "Barrie", province: "ontario", population: "147,000", descriptor: "Simcoe County's gateway to cottage country", industries: ["Manufacturing", "Healthcare", "Construction", "Retail", "Tourism", "Technology"], areas: ["Downtown Barrie", "Allandale", "Painswick", "Holly", "East Bayfield"], fact: "one of Canada's fastest-growing metro areas", lat: 44.3894, lng: -79.6903 },
  { slug: "st-catharines", name: "St. Catharines", province: "ontario", population: "136,000", descriptor: "the largest city in the Niagara region", industries: ["Manufacturing", "Wine and agri-food", "Education", "Healthcare", "Tourism"], areas: ["Downtown St. Catharines", "Port Dalhousie", "Merritton", "Grantham", "Western Hill"], fact: "the 'Garden City' at the heart of Niagara wine country", lat: 43.1594, lng: -79.2469 },
  { slug: "guelph", name: "Guelph", province: "ontario", population: "144,000", descriptor: "a university city with a strong agri-tech and manufacturing base", industries: ["Agri-food", "Manufacturing", "Education", "Technology", "Healthcare"], areas: ["Downtown Guelph", "The Ward", "Kortright Hills", "Westminster Woods", "Exhibition Park"], fact: "home to the University of Guelph and one of Canada's lowest unemployment rates", lat: 43.5448, lng: -80.2482 },
  { slug: "kingston", name: "Kingston", province: "ontario", population: "132,000", descriptor: "a historic limestone city on Lake Ontario", industries: ["Education", "Healthcare", "Government", "Tourism", "Technology"], areas: ["Downtown Kingston", "Portsmouth", "Kingscourt", "Cataraqui", "Sydenham"], fact: "home to Queen's University and Canada's first capital", lat: 44.2312, lng: -76.486 },
  { slug: "waterloo", name: "Waterloo", province: "ontario", population: "121,000", descriptor: "a global technology and innovation hub", industries: ["Technology", "Insurance", "Education", "Research", "Professional services"], areas: ["Uptown Waterloo", "David Johnston Research + Technology Park", "Laurelwood", "Beechwood", "Lakeshore"], fact: "home to the University of Waterloo, Perimeter Institute and hundreds of startups", lat: 43.4643, lng: -80.5204 },
  { slug: "thunder-bay", name: "Thunder Bay", province: "ontario", population: "108,000", descriptor: "Northwestern Ontario's commercial hub on Lake Superior", industries: ["Healthcare", "Education", "Forestry", "Mining services", "Transportation", "Tourism"], areas: ["Port Arthur", "Fort William", "Westfort", "Current River", "Intercity"], fact: "the regional centre for a vast mining and forestry economy", lat: 48.3809, lng: -89.2477 },
  { slug: "sudbury", name: "Greater Sudbury", province: "ontario", population: "166,000", descriptor: "the largest city in Northern Ontario", industries: ["Mining", "Healthcare", "Education", "Retail", "Mining technology"], areas: ["Downtown Sudbury", "New Sudbury", "South End", "Valley East", "Copper Cliff"], fact: "a world centre of mining innovation and home to Science North", lat: 46.4917, lng: -80.993 },
  { slug: "niagara-falls", name: "Niagara Falls", province: "ontario", population: "94,000", descriptor: "one of the world's most visited tourism destinations", industries: ["Tourism", "Hospitality", "Retail", "Entertainment", "Construction"], areas: ["Clifton Hill", "Fallsview", "Lundy's Lane", "Chippawa", "Stamford"], fact: "welcomes more than 13 million visitors a year", lat: 43.0896, lng: -79.0849 },

  // Quebec
  { slug: "montreal", name: "Montreal", province: "quebec", population: "1.8 million", descriptor: "Canada's cultural capital and a global AI and gaming hub", industries: ["Technology", "Aerospace", "Artificial intelligence", "Video games", "Finance", "Fashion", "Tourism"], areas: ["Plateau-Mont-Royal", "Old Montreal", "Mile End", "Griffintown", "Westmount", "Laval border", "Downtown"], fact: "home to Mila, one of the world's largest academic AI research institutes", lat: 45.5017, lng: -73.5673, major: true },
  { slug: "quebec-city", name: "Quebec City", province: "quebec", population: "550,000", descriptor: "the provincial capital and a UNESCO World Heritage city", industries: ["Government", "Insurance", "Technology", "Tourism", "Healthcare", "Optics and photonics"], areas: ["Vieux-Québec", "Sainte-Foy", "Limoilou", "Beauport", "Charlesbourg", "Lebourgneuf"], fact: "a leader in optics-photonics and insurance technology", lat: 46.8139, lng: -71.208, major: true },
  { slug: "laval", name: "Laval", province: "quebec", population: "438,000", descriptor: "Quebec's third-largest city just north of Montreal", industries: ["Pharmaceuticals", "Life sciences", "Retail", "Manufacturing", "Agri-food"], areas: ["Chomedey", "Sainte-Rose", "Vimont", "Duvernay", "Laval-des-Rapides"], fact: "home to Cité de la Biotech, one of Canada's largest life-science parks", lat: 45.6066, lng: -73.7124 },
  { slug: "gatineau", name: "Gatineau", province: "quebec", population: "292,000", descriptor: "Ottawa's bilingual sister city across the river", industries: ["Government", "Technology", "Healthcare", "Construction", "Retail"], areas: ["Hull", "Aylmer", "Buckingham", "Masson-Angers", "Plateau"], fact: "part of the National Capital Region with a uniquely bilingual consumer base", lat: 45.4765, lng: -75.7013 },
  { slug: "longueuil", name: "Longueuil", province: "quebec", population: "254,000", descriptor: "the largest city on Montreal's South Shore", industries: ["Aerospace", "Manufacturing", "Healthcare", "Retail", "Logistics"], areas: ["Vieux-Longueuil", "Saint-Hubert", "Greenfield Park", "Boucherville border"], fact: "home to Pratt & Whitney Canada and the Canadian Space Agency", lat: 45.5312, lng: -73.5181 },
  { slug: "sherbrooke", name: "Sherbrooke", province: "quebec", population: "172,000", descriptor: "the university city of the Eastern Townships", industries: ["Education", "Healthcare", "Technology", "Manufacturing", "Tourism"], areas: ["Centre-ville", "Fleurimont", "Rock Forest", "Lennoxville", "Brompton"], fact: "home to Université de Sherbrooke and Bishop's University", lat: 45.4042, lng: -71.8929 },
  { slug: "levis", name: "Lévis", province: "quebec", population: "149,000", descriptor: "a thriving city across the river from Quebec City", industries: ["Financial services", "Manufacturing", "Shipbuilding", "Retail", "Construction"], areas: ["Vieux-Lévis", "Saint-Romuald", "Charny", "Saint-Nicolas", "Saint-Jean-Chrysostome"], fact: "headquarters of Desjardins Group, North America's largest federation of credit unions", lat: 46.8033, lng: -71.1779 },
  { slug: "trois-rivieres", name: "Trois-Rivières", province: "quebec", population: "139,000", descriptor: "the historic capital of the Mauricie region", industries: ["Manufacturing", "Education", "Healthcare", "Energy", "Retail"], areas: ["Centre-ville", "Cap-de-la-Madeleine", "Trois-Rivières-Ouest", "Pointe-du-Lac"], fact: "one of North America's oldest cities, founded in 1634", lat: 46.3432, lng: -72.5477 },
  { slug: "saguenay", name: "Saguenay", province: "quebec", population: "145,000", descriptor: "the industrial and cultural heart of the Saguenay–Lac-Saint-Jean region", industries: ["Aluminum", "Forestry", "Healthcare", "Education", "Tourism"], areas: ["Chicoutimi", "Jonquière", "La Baie", "Arvida"], fact: "a global centre of aluminum production and fjord tourism", lat: 48.428, lng: -71.0686 },

  // British Columbia
  { slug: "vancouver", name: "Vancouver", province: "british-columbia", population: "662,000", descriptor: "Canada's Pacific gateway and a global tech and film city", industries: ["Technology", "Film and TV", "Real estate", "Tourism", "Finance", "Green energy"], areas: ["Downtown", "Yaletown", "Gastown", "Kitsilano", "Mount Pleasant", "West End", "Kerrisdale"], fact: "North America's third-largest film production centre", lat: 49.2827, lng: -123.1207, major: true },
  { slug: "surrey", name: "Surrey", province: "british-columbia", population: "568,000", descriptor: "BC's fastest-growing city and future largest", industries: ["Construction", "Healthcare", "Manufacturing", "Logistics", "Education", "Retail"], areas: ["City Centre", "Guildford", "Newton", "Cloverdale", "South Surrey", "Fleetwood"], fact: "welcomes roughly 1,000 new residents every month", lat: 49.1913, lng: -122.849, major: true },
  { slug: "burnaby", name: "Burnaby", province: "british-columbia", population: "249,000", descriptor: "a major business and education centre in Metro Vancouver", industries: ["Technology", "Film", "Education", "Retail", "Manufacturing"], areas: ["Metrotown", "Brentwood", "Lougheed", "Edmonds", "Burnaby Heights"], fact: "home to Simon Fraser University and Canada's largest concentration of film studios", lat: 49.2488, lng: -122.9805 },
  { slug: "richmond", name: "Richmond", province: "british-columbia", population: "209,000", descriptor: "an island city hosting Vancouver International Airport", industries: ["Aviation", "Logistics", "Technology", "Retail", "Agriculture"], areas: ["City Centre", "Steveston", "Ironwood", "Hamilton", "Thompson"], fact: "one of Canada's most multicultural cities with a thriving Asian-Canadian business community", lat: 49.1666, lng: -123.1336 },
  { slug: "kelowna", name: "Kelowna", province: "british-columbia", population: "144,000", descriptor: "the Okanagan's sun-soaked tech and tourism capital", industries: ["Technology", "Tourism", "Wine", "Healthcare", "Construction", "Real estate"], areas: ["Downtown Kelowna", "Glenmore", "Rutland", "Mission", "West Kelowna"], fact: "one of Canada's fastest-growing tech ecosystems outside a major metro", lat: 49.888, lng: -119.496 },
  { slug: "victoria", name: "Victoria", province: "british-columbia", population: "92,000", descriptor: "BC's capital and a hub for government, tech and tourism", industries: ["Government", "Technology", "Tourism", "Education", "Marine", "Healthcare"], areas: ["Downtown Victoria", "James Bay", "Oak Bay", "Saanich", "Langford", "Esquimalt"], fact: "home to one of Canada's most concentrated tech sectors per capita", lat: 48.4284, lng: -123.3656, major: true },
  { slug: "abbotsford", name: "Abbotsford", province: "british-columbia", population: "153,000", descriptor: "the largest city in the Fraser Valley", industries: ["Agriculture", "Aerospace", "Manufacturing", "Healthcare", "Retail"], areas: ["Downtown Abbotsford", "Clearbrook", "Matsqui", "Sumas", "Mission border"], fact: "Canada's most productive agricultural community", lat: 49.0504, lng: -122.3045 },
  { slug: "coquitlam", name: "Coquitlam", province: "british-columbia", population: "149,000", descriptor: "a growing family-oriented city in the Tri-Cities", industries: ["Retail", "Construction", "Healthcare", "Education", "Professional services"], areas: ["Coquitlam Centre", "Burquitlam", "Maillardville", "Westwood Plateau", "Austin Heights"], fact: "one of Metro Vancouver's fastest-growing municipalities along the Evergreen Line", lat: 49.2838, lng: -122.7932 },
  { slug: "langley", name: "Langley", province: "british-columbia", population: "160,000", descriptor: "a fast-growing township and city in the Fraser Valley", industries: ["Manufacturing", "Agriculture", "Construction", "Retail", "Film"], areas: ["Willoughby", "Walnut Grove", "Fort Langley", "Brookswood", "Aldergrove"], fact: "home to one of BC's highest concentrations of small businesses", lat: 49.1044, lng: -122.6604 },
  { slug: "nanaimo", name: "Nanaimo", province: "british-columbia", population: "100,000", descriptor: "Vancouver Island's central harbour city", industries: ["Healthcare", "Education", "Tourism", "Construction", "Marine", "Technology"], areas: ["Downtown Nanaimo", "Departure Bay", "North Nanaimo", "Harewood", "Lantzville"], fact: "the gateway to Vancouver Island's fast-growing mid-island region", lat: 49.1659, lng: -123.9401 },
  { slug: "kamloops", name: "Kamloops", province: "british-columbia", population: "98,000", descriptor: "the tournament capital of Canada in BC's interior", industries: ["Healthcare", "Education", "Transportation", "Mining", "Tourism", "Retail"], areas: ["Downtown Kamloops", "North Shore", "Sahali", "Aberdeen", "Valleyview"], fact: "a key transportation and services hub at the junction of the Thompson rivers", lat: 50.6745, lng: -120.3273 },
  { slug: "prince-george", name: "Prince George", province: "british-columbia", population: "77,000", descriptor: "Northern BC's capital", industries: ["Forestry", "Healthcare", "Education", "Transportation", "Mining services"], areas: ["Downtown Prince George", "College Heights", "Hart Highlands", "Westwood"], fact: "the service centre for a region larger than many countries", lat: 53.9171, lng: -122.7497 },

  // Alberta
  { slug: "calgary", name: "Calgary", province: "alberta", population: "1.3 million", descriptor: "Canada's energy capital and a rising tech hub", industries: ["Energy", "Technology", "Finance", "Logistics", "Agriculture", "Professional services"], areas: ["Downtown", "Beltline", "Kensington", "Inglewood", "Mission", "Quarry Park", "Northeast Calgary"], fact: "home to the second-highest number of corporate head offices in Canada", lat: 51.0447, lng: -114.0719, major: true },
  { slug: "edmonton", name: "Edmonton", province: "alberta", population: "1.0 million", descriptor: "Alberta's capital and a leader in AI and health innovation", industries: ["Government", "Healthcare", "Technology", "Energy services", "Education", "Construction"], areas: ["Downtown", "Whyte Avenue", "Oliver", "West Edmonton", "Windermere", "Sherwood Park"], fact: "home to Amii, a world-leading AI research institute, and the University of Alberta", lat: 53.5461, lng: -113.4938, major: true },
  { slug: "red-deer", name: "Red Deer", province: "alberta", population: "100,000", descriptor: "the commercial hub midway between Calgary and Edmonton", industries: ["Energy services", "Agriculture", "Healthcare", "Manufacturing", "Retail"], areas: ["Downtown Red Deer", "Gasoline Alley", "Clearview", "Timberlands", "Inglewood"], fact: "serves a trading area of more than 300,000 central Albertans", lat: 52.2681, lng: -113.8112 },
  { slug: "lethbridge", name: "Lethbridge", province: "alberta", population: "98,000", descriptor: "Southern Alberta's agri-food and education centre", industries: ["Agri-food", "Education", "Healthcare", "Manufacturing", "Retail"], areas: ["Downtown Lethbridge", "West Lethbridge", "Southside", "Northside"], fact: "the heart of Canada's largest irrigated agriculture district", lat: 49.6956, lng: -112.8451 },
  { slug: "st-albert", name: "St. Albert", province: "alberta", population: "69,000", descriptor: "an affluent community on Edmonton's northwest edge", industries: ["Professional services", "Retail", "Healthcare", "Construction", "Education"], areas: ["Downtown St. Albert", "Erin Ridge", "Riverside", "Grandin", "Lacombe Park"], fact: "consistently ranked among Canada's best places to live", lat: 53.6305, lng: -113.6256 },
  { slug: "medicine-hat", name: "Medicine Hat", province: "alberta", population: "63,000", descriptor: "the sunniest city in Canada", industries: ["Energy", "Agriculture", "Manufacturing", "Healthcare", "Retail"], areas: ["Downtown Medicine Hat", "Crescent Heights", "Southview", "Ross Glen"], fact: "known as 'The Gas City' for its natural-gas heritage", lat: 50.0405, lng: -110.6764 },
  { slug: "grande-prairie", name: "Grande Prairie", province: "alberta", population: "64,000", descriptor: "the fast-growing hub of the Peace Region", industries: ["Energy", "Forestry", "Agriculture", "Construction", "Retail"], areas: ["Downtown Grande Prairie", "Westgate", "Countryside", "Mission Heights"], fact: "one of Canada's youngest cities by median age", lat: 55.1707, lng: -118.7947 },
  { slug: "airdrie", name: "Airdrie", province: "alberta", population: "74,000", descriptor: "a booming commuter city north of Calgary", industries: ["Construction", "Retail", "Logistics", "Professional services", "Healthcare"], areas: ["Downtown Airdrie", "Coopers Crossing", "Bayside", "Kings Heights", "Reunion"], fact: "one of Canada's fastest-growing municipalities over the past decade", lat: 51.2917, lng: -114.0144 },

  // Manitoba
  { slug: "winnipeg", name: "Winnipeg", province: "manitoba", population: "749,000", descriptor: "the Gateway to the West and Manitoba's capital", industries: ["Manufacturing", "Finance", "Transportation", "Aerospace", "Agriculture", "Healthcare"], areas: ["Downtown", "The Exchange District", "Osborne Village", "St. Boniface", "St. Vital", "Transcona"], fact: "home to Canada's largest concentration of aerospace manufacturers outside Montreal", lat: 49.8951, lng: -97.1384, major: true },
  { slug: "brandon", name: "Brandon", province: "manitoba", population: "51,000", descriptor: "Manitoba's second city and agricultural hub", industries: ["Agriculture", "Food processing", "Healthcare", "Education", "Retail"], areas: ["Downtown Brandon", "West End", "North Hill", "Riverheights"], fact: "the 'Wheat City' serving Western Manitoba's farm economy", lat: 49.8483, lng: -99.95 },

  // Saskatchewan
  { slug: "saskatoon", name: "Saskatoon", province: "saskatchewan", population: "266,000", descriptor: "Saskatchewan's largest city and innovation centre", industries: ["Mining", "Agriculture", "Technology", "Education", "Healthcare", "Construction"], areas: ["Downtown Saskatoon", "Broadway", "Riversdale", "Stonebridge", "Evergreen", "Sutherland"], fact: "home to the Canadian Light Source synchrotron and a global agri-tech cluster", lat: 52.1332, lng: -106.67, major: true },
  { slug: "regina", name: "Regina", province: "saskatchewan", population: "226,000", descriptor: "Saskatchewan's capital and the Queen City", industries: ["Government", "Insurance", "Agriculture", "Energy", "Technology", "Manufacturing"], areas: ["Downtown Regina", "Cathedral", "Harbour Landing", "Warehouse District", "Lakeview"], fact: "headquarters to major Canadian insurers and crown corporations", lat: 50.4452, lng: -104.6189, major: true },

  // Nova Scotia
  { slug: "halifax", name: "Halifax", province: "nova-scotia", population: "440,000", descriptor: "Atlantic Canada's largest city and economic engine", industries: ["Ocean technology", "Defence", "Finance", "Education", "Healthcare", "Tourism"], areas: ["Downtown Halifax", "North End", "Dartmouth", "Bedford", "Clayton Park", "Spryfield"], fact: "home to six universities and Canada's east-coast naval base", lat: 44.6488, lng: -63.5752, major: true },
  { slug: "sydney", name: "Sydney", province: "nova-scotia", population: "30,000", descriptor: "the urban heart of Cape Breton Island", industries: ["Healthcare", "Education", "Tourism", "Customer service", "Marine"], areas: ["Downtown Sydney", "Whitney Pier", "Ashby", "Sydney River"], fact: "home to Cape Breton University and a revitalized waterfront", lat: 46.1368, lng: -60.1942 },

  // New Brunswick
  { slug: "moncton", name: "Moncton", province: "new-brunswick", population: "158,000", descriptor: "Atlantic Canada's fastest-growing bilingual city", industries: ["Logistics", "Customer service", "Healthcare", "Retail", "Technology", "Insurance"], areas: ["Downtown Moncton", "Dieppe", "Riverview", "North End", "Magnetic Hill"], fact: "the 'Hub City' at the crossroads of the Maritimes", lat: 46.0878, lng: -64.7782, major: true },
  { slug: "saint-john", name: "Saint John", province: "new-brunswick", population: "130,000", descriptor: "Canada's oldest incorporated city on the Bay of Fundy", industries: ["Energy", "Port and logistics", "IT and customer service", "Healthcare", "Tourism"], areas: ["Uptown Saint John", "Rothesay", "Quispamsis", "West Side", "East Side"], fact: "home to Canada's largest oil refinery and a deep-water port", lat: 45.2733, lng: -66.0633 },
  { slug: "fredericton", name: "Fredericton", province: "new-brunswick", population: "108,000", descriptor: "New Brunswick's capital and cybersecurity hub", industries: ["Government", "Cybersecurity", "Education", "Technology", "Healthcare"], areas: ["Downtown Fredericton", "Northside", "Silverwood", "Marysville", "Knowledge Park"], fact: "home to the Canadian Institute for Cybersecurity at UNB", lat: 45.9636, lng: -66.6431 },

  // Newfoundland and Labrador
  { slug: "st-johns", name: "St. John's", province: "newfoundland-and-labrador", population: "212,000", descriptor: "North America's oldest city and NL's capital", industries: ["Offshore energy", "Ocean technology", "Healthcare", "Education", "Tourism", "Technology"], areas: ["Downtown St. John's", "Mount Pearl", "Paradise", "Kenmount", "Churchill Square"], fact: "home to Memorial University and a booming ocean-tech startup scene", lat: 47.5615, lng: -52.7126, major: true },

  // PEI
  { slug: "charlottetown", name: "Charlottetown", province: "prince-edward-island", population: "78,000", descriptor: "the birthplace of Confederation", industries: ["Government", "Tourism", "Bioscience", "Education", "Retail", "Agriculture"], areas: ["Downtown Charlottetown", "Stratford", "Cornwall", "West Royalty", "Sherwood"], fact: "home to a fast-growing bioscience cluster and vibrant tourism economy", lat: 46.2382, lng: -63.1311, major: true },

  // Territories
  { slug: "yellowknife", name: "Yellowknife", province: "northwest-territories", population: "20,000", descriptor: "the diamond capital of North America", industries: ["Mining", "Government", "Tourism", "Construction", "Aviation"], areas: ["Downtown Yellowknife", "Old Town", "Frame Lake", "Range Lake", "Niven"], fact: "one of the world's best places to see the northern lights", lat: 62.454, lng: -114.3718, major: true },
  { slug: "whitehorse", name: "Whitehorse", province: "yukon", population: "28,000", descriptor: "the Wilderness City and Yukon's capital", industries: ["Government", "Tourism", "Mining", "Construction", "Retail"], areas: ["Downtown Whitehorse", "Riverdale", "Porter Creek", "Whistle Bend", "Copper Ridge"], fact: "home to roughly 70% of Yukon's population", lat: 60.7212, lng: -135.0568, major: true },
  { slug: "iqaluit", name: "Iqaluit", province: "nunavut", population: "7,500", descriptor: "Canada's northernmost capital on Baffin Island", industries: ["Government", "Construction", "Arts and culture", "Transportation", "Retail"], areas: ["Downtown Iqaluit", "Happy Valley", "Tundra Valley", "Apex"], fact: "the fastest-growing capital city in Canada by percentage", lat: 63.7467, lng: -68.517, major: true },
];

export const getProvince = (slug: string) => provinces.find((p) => p.slug === slug);
export const getCity = (slug: string) => cities.find((c) => c.slug === slug);
export const getCitiesInProvince = (provinceSlug: string) => cities.filter((c) => c.province === provinceSlug);
export const majorCities = cities.filter((c) => c.major);

export const getNearbyCities = (city: City, limit = 6) =>
  cities
    .filter((c) => c.slug !== city.slug)
    .map((c) => ({ c, d: Math.hypot(c.lat - city.lat, (c.lng - city.lng) * Math.cos((city.lat * Math.PI) / 180)) }))
    .sort((a, b) => a.d - b.d)
    .slice(0, limit)
    .map((x) => x.c);
