// Generated by scripts/gen-extra-cities.mjs from research/data/cities. Do not edit by hand.
import type { City } from "./locations";

export const extraCities: City[] = [
  {
    "slug": "etobicoke",
    "name": "Etobicoke",
    "province": "ontario",
    "population": "376,000",
    "descriptor": "the western district of the City of Toronto and a former city",
    "industries": [
      "Hospitality",
      "Tourism",
      "Education",
      "Transportation",
      "Real estate"
    ],
    "areas": [
      "Mimico",
      "New Toronto",
      "Long Branch",
      "The Kingsway",
      "Islington",
      "Rexdale"
    ],
    "fact": "home to Woodbine Racetrack, the Great Canadian Casino Resort and two Humber Polytechnic campuses",
    "lat": 43.6205,
    "lng": -79.5132,
    "parent": "toronto"
  },
  {
    "slug": "north-york",
    "name": "North York",
    "province": "ontario",
    "population": "684,000",
    "descriptor": "a district of the City of Toronto and the former City of North York",
    "industries": [
      "Education",
      "Retail",
      "Construction",
      "Real estate",
      "Transportation"
    ],
    "areas": [
      "Willowdale",
      "Don Mills",
      "Downsview",
      "York Mills",
      "Bayview Village",
      "Newtonbrook"
    ],
    "fact": "home to York University's Keele Campus, where more than 52,000 students are enrolled",
    "lat": 43.7615,
    "lng": -79.4111,
    "parent": "toronto"
  },
  {
    "slug": "scarborough",
    "name": "Scarborough",
    "province": "ontario",
    "population": "624,000",
    "descriptor": "the eastern district of the City of Toronto and a former city",
    "industries": [
      "Education",
      "Construction",
      "Transportation",
      "Retail"
    ],
    "areas": [
      "Agincourt",
      "Malvern",
      "Guildwood",
      "Birch Cliff",
      "Wexford"
    ],
    "fact": "home to Centennial College's largest campus and the University of Toronto Scarborough",
    "lat": 43.7731,
    "lng": -79.2578,
    "parent": "toronto"
  },
  {
    "slug": "cambridge",
    "name": "Cambridge",
    "province": "ontario",
    "population": "138,000",
    "descriptor": "a manufacturing city in Waterloo Region on the Grand River",
    "industries": [
      "Manufacturing",
      "Automotive",
      "Aerospace",
      "Energy",
      "Logistics",
      "Retail"
    ],
    "areas": [
      "Galt",
      "Preston",
      "Hespeler",
      "Blair"
    ],
    "fact": "home to two Toyota assembly plants and a workforce nearly one-fifth in advanced manufacturing",
    "lat": 43.3616,
    "lng": -80.3144
  },
  {
    "slug": "whitby",
    "name": "Whitby",
    "province": "ontario",
    "population": "139,000",
    "descriptor": "a growing lakeshore town in Durham Region east of Toronto",
    "industries": [
      "Manufacturing",
      "Professional services",
      "Technology",
      "Healthcare",
      "Logistics",
      "Retail"
    ],
    "areas": [
      "Downtown Whitby",
      "Brooklin",
      "Port Whitby",
      "Williamsburg",
      "Pringle Creek",
      "Taunton North"
    ],
    "fact": "home to 3,493 businesses that employ approximately 43,300 people",
    "lat": 43.8975,
    "lng": -78.9429
  },
  {
    "slug": "milton",
    "name": "Milton",
    "province": "ontario",
    "population": "133,000",
    "descriptor": "a fast-growing town in Halton Region",
    "industries": [
      "Manufacturing",
      "Logistics",
      "Education",
      "Professional services",
      "Retail",
      "Construction"
    ],
    "areas": [
      "Old Milton",
      "Timberlea",
      "Dempsey",
      "Campbellville"
    ],
    "fact": "home to the Milton Education Village, where Conestoga College and Wilfrid Laurier University opened campuses",
    "lat": 43.5183,
    "lng": -79.8774
  },
  {
    "slug": "ajax",
    "name": "Ajax",
    "province": "ontario",
    "population": "127,000",
    "descriptor": "a lakeshore town in Durham Region east of Toronto",
    "industries": [
      "Manufacturing",
      "Logistics",
      "Healthcare",
      "Insurance",
      "Energy",
      "Tourism"
    ],
    "areas": [
      "Pickering Village",
      "Downtown Ajax",
      "Southwood",
      "Applecroft",
      "Discovery Bay",
      "Westney Heights"
    ],
    "fact": "a town where manufacturing is the largest employment sector, with 28% of local jobs",
    "lat": 43.8509,
    "lng": -79.0204
  },
  {
    "slug": "chatham-kent",
    "name": "Chatham-Kent",
    "province": "ontario",
    "population": "104,000",
    "descriptor": "a large rural municipality in southwestern Ontario on the Thames River",
    "industries": [
      "Agriculture",
      "Agri-food",
      "Food processing",
      "Manufacturing",
      "Healthcare"
    ],
    "areas": [
      "Chatham",
      "Wallaceburg",
      "Tilbury",
      "Blenheim",
      "Ridgetown",
      "Dresden"
    ],
    "fact": "Canada's top producer of tomatoes, seed corn and pumpkins",
    "lat": 42.4048,
    "lng": -82.191
  },
  {
    "slug": "clarington",
    "name": "Clarington",
    "province": "ontario",
    "population": "101,000",
    "descriptor": "a growing lakeshore municipality at the eastern edge of the GTA",
    "industries": [
      "Energy",
      "Construction",
      "Manufacturing",
      "Agriculture",
      "Retail"
    ],
    "areas": [
      "Bowmanville",
      "Courtice",
      "Newcastle",
      "Orono"
    ],
    "fact": "home to the Darlington Nuclear site, where up to four small modular reactors are planned",
    "lat": 43.9126,
    "lng": -78.6876
  },
  {
    "slug": "pickering",
    "name": "Pickering",
    "province": "ontario",
    "population": "99,000",
    "descriptor": "a lakeshore city in Durham Region on Toronto's eastern border",
    "industries": [
      "Energy",
      "Manufacturing",
      "Food processing",
      "Logistics",
      "Construction",
      "Retail"
    ],
    "areas": [
      "Bay Ridges",
      "Amberlea",
      "Dunbarton",
      "Duffin Heights",
      "Rougemount",
      "Liverpool"
    ],
    "fact": "home to the Pickering Nuclear Generating Station and the planned Seaton community",
    "lat": 43.8384,
    "lng": -79.0868
  },
  {
    "slug": "newmarket",
    "name": "Newmarket",
    "province": "ontario",
    "population": "88,000",
    "descriptor": "a compact town in York Region north of Toronto",
    "industries": [
      "Healthcare",
      "Retail",
      "Professional services",
      "Technology",
      "Manufacturing"
    ],
    "areas": [
      "Central Newmarket",
      "Stonehaven",
      "Summerhill Estates",
      "Woodland Hill",
      "Glenway"
    ],
    "fact": "home to Southlake Regional Health Centre, its largest employer with over 3,000 staff",
    "lat": 44.0592,
    "lng": -79.4613
  },
  {
    "slug": "brantford",
    "name": "Brantford",
    "province": "ontario",
    "population": "105,000",
    "descriptor": "a Grand River city in southwestern Ontario",
    "industries": [
      "Manufacturing",
      "Food processing",
      "Logistics",
      "Retail",
      "Healthcare"
    ],
    "areas": [
      "Eagle Place",
      "Holmedale",
      "West Brant",
      "Echo Place",
      "Terrace Hill"
    ],
    "fact": "home to about 20 food and beverage manufacturers employing approximately 2,300 people",
    "lat": 43.1394,
    "lng": -80.2644
  },
  {
    "slug": "kawartha-lakes",
    "name": "Kawartha Lakes",
    "province": "ontario",
    "population": "79,000",
    "descriptor": "a large rural city of lakes and small towns in central Ontario",
    "industries": [
      "Tourism",
      "Agriculture",
      "Manufacturing",
      "Retail",
      "Healthcare",
      "Government"
    ],
    "areas": [
      "Lindsay",
      "Bobcaygeon",
      "Fenelon Falls",
      "Omemee",
      "Woodville",
      "Coboconk"
    ],
    "fact": "home to Ross Memorial Hospital, a 198-bed hospital in Lindsay with more than 950 staff",
    "lat": 44.3501,
    "lng": -78.74
  },
  {
    "slug": "sault-ste-marie",
    "name": "Sault Ste. Marie",
    "province": "ontario",
    "population": "72,000",
    "descriptor": "a steel-making city on the St. Marys River in Northern Ontario",
    "industries": [
      "Manufacturing",
      "Healthcare",
      "Education",
      "Forestry",
      "Government",
      "Retail"
    ],
    "areas": [
      "Downtown",
      "Steelton",
      "Korah",
      "Tarentorus",
      "Pointe des Chênes"
    ],
    "fact": "home to Algoma Steel, which is building two electric arc furnaces to replace its blast furnace",
    "lat": 46.5219,
    "lng": -84.3461
  },
  {
    "slug": "halton-hills",
    "name": "Halton Hills",
    "province": "ontario",
    "population": "63,000",
    "descriptor": "a town of rural hamlets and two urban centres in Halton Region",
    "industries": [
      "Logistics",
      "Manufacturing",
      "Retail",
      "Agriculture"
    ],
    "areas": [
      "Georgetown",
      "Acton",
      "Glen Williams",
      "Limehouse",
      "Terra Cotta",
      "Norval"
    ],
    "fact": "home to the Premier Gateway employment area where Highways 401 and 407 meet",
    "lat": 43.63,
    "lng": -79.95
  },
  {
    "slug": "peterborough",
    "name": "Peterborough",
    "province": "ontario",
    "population": "84,000",
    "descriptor": "a university and hospital city on the Otonabee River in central Ontario",
    "industries": [
      "Healthcare",
      "Education",
      "Manufacturing",
      "Food processing",
      "Energy",
      "Government"
    ],
    "areas": [
      "Downtown",
      "East City",
      "Ashburnham",
      "Kawartha Heights",
      "Northcrest",
      "Jackson Park"
    ],
    "fact": "home to Peterborough Regional Health Centre, the region's largest employer with more than 3,100 staff",
    "lat": 44.3091,
    "lng": -78.3197
  },
  {
    "slug": "aurora",
    "name": "Aurora",
    "province": "ontario",
    "population": "62,000",
    "descriptor": "a fast-growing town in York Region north of Toronto",
    "industries": [
      "Automotive",
      "Manufacturing",
      "Technology",
      "Finance",
      "Insurance",
      "Food processing"
    ],
    "areas": [
      "Aurora Village",
      "Aurora Heights",
      "Aurora Highlands",
      "Bayview Wellington",
      "Aurora Grove"
    ],
    "fact": "home to the headquarters of auto parts maker Magna International",
    "lat": 44.0065,
    "lng": -79.4504
  },
  {
    "slug": "welland",
    "name": "Welland",
    "province": "ontario",
    "population": "56,000",
    "descriptor": "a canal city in the Niagara Region of southern Ontario",
    "industries": [
      "Manufacturing",
      "Education",
      "Tourism",
      "Retail",
      "Logistics"
    ],
    "areas": [
      "Downtown Welland",
      "Dain City",
      "Cooks Mills",
      "Crowland",
      "Hunters Pointe"
    ],
    "fact": "home to Niagara College's Welland Campus and its Walker Advanced Manufacturing Innovation Centre",
    "lat": 42.9922,
    "lng": -79.2483
  },
  {
    "slug": "belleville",
    "name": "Belleville",
    "province": "ontario",
    "population": "55,000",
    "descriptor": "a city on the Bay of Quinte in eastern Ontario",
    "industries": [
      "Food processing",
      "Manufacturing",
      "Healthcare",
      "Education",
      "Retail",
      "Logistics"
    ],
    "areas": [
      "Downtown Belleville",
      "Thurlow",
      "Cannifton",
      "Foxboro",
      "Point Anne",
      "Corbyville"
    ],
    "fact": "home to a WK Kellogg Co plant that makes Mini Wheats, Corn Pops and All Bran Buds",
    "lat": 44.1628,
    "lng": -77.3832
  },
  {
    "slug": "north-bay",
    "name": "North Bay",
    "province": "ontario",
    "population": "53,000",
    "descriptor": "a regional service city on Lake Nipissing in northeastern Ontario",
    "industries": [
      "Mining",
      "Education",
      "Healthcare",
      "Aerospace",
      "Government",
      "Retail"
    ],
    "areas": [
      "Downtown North Bay",
      "West Ferris",
      "Widdifield",
      "Thibeault Terrace"
    ],
    "fact": "home to more than 60 mining supply and services businesses, though there are no mines in the city",
    "lat": 46.3091,
    "lng": -79.4608
  },
  {
    "slug": "caledon",
    "name": "Caledon",
    "province": "ontario",
    "population": "77,000",
    "descriptor": "a fast-growing town of villages and farmland in Peel Region",
    "industries": [
      "Logistics",
      "Construction",
      "Manufacturing",
      "Agriculture",
      "Food processing",
      "Tourism"
    ],
    "areas": [
      "Bolton",
      "Caledon East",
      "Caledon Village",
      "Inglewood",
      "Palgrave",
      "Alton"
    ],
    "fact": "home to UPS Canada's $200-million, 850,000-square-foot sortation facility",
    "lat": 43.8668,
    "lng": -79.858
  },
  {
    "slug": "cornwall",
    "name": "Cornwall",
    "province": "ontario",
    "population": "48,000",
    "descriptor": "a St. Lawrence River city in eastern Ontario near the Quebec border",
    "industries": [
      "Logistics",
      "Retail",
      "Healthcare",
      "Manufacturing",
      "Transportation"
    ],
    "areas": [
      "Downtown Cornwall",
      "Le Village",
      "Riverdale",
      "Eamer's Corners"
    ],
    "fact": "home to over five million square feet of distribution centres in Cornwall Business Park",
    "lat": 45.0213,
    "lng": -74.7303
  },
  {
    "slug": "georgina",
    "name": "Georgina",
    "province": "ontario",
    "population": "48,000",
    "descriptor": "a lakeside town on the south shore of Lake Simcoe in York Region",
    "industries": [
      "Tourism",
      "Construction",
      "Manufacturing",
      "Retail",
      "Hospitality"
    ],
    "areas": [
      "Keswick",
      "Sutton",
      "Jackson's Point",
      "Pefferlaw",
      "Baldwin",
      "Udora"
    ],
    "fact": "home to more than 3,400 businesses, most of them owner-operated",
    "lat": 44.2965,
    "lng": -79.4366
  },
  {
    "slug": "whitchurch-stouffville",
    "name": "Whitchurch-Stouffville",
    "province": "ontario",
    "population": "50,000",
    "descriptor": "a growing commuter town on the Oak Ridges Moraine in York Region",
    "industries": [
      "Manufacturing",
      "Transportation",
      "Agriculture",
      "Construction",
      "Retail"
    ],
    "areas": [
      "Stouffville",
      "Gormley",
      "Ballantrae",
      "Musselman Lake",
      "Vandorf",
      "Bloomington"
    ],
    "fact": "home to the Gormley employment lands on Highway 404 and a GO train station on Main Street",
    "lat": 43.9703,
    "lng": -79.2445
  },
  {
    "slug": "woodstock",
    "name": "Woodstock",
    "province": "ontario",
    "population": "47,000",
    "descriptor": "a fast-growing city in Oxford County at the junction of Highways 401 and 403",
    "industries": [
      "Automotive",
      "Manufacturing",
      "Logistics",
      "Agriculture"
    ],
    "areas": [
      "Downtown Woodstock",
      "South End",
      "East Woodstock",
      "North East Business Park"
    ],
    "fact": "home to a Toyota assembly plant and a cluster of auto parts suppliers that together employ thousands",
    "lat": 43.1315,
    "lng": -80.7472
  },
  {
    "slug": "quinte-west",
    "name": "Quinte West",
    "province": "ontario",
    "population": "47,000",
    "descriptor": "a city on the Bay of Quinte and the Trent-Severn Waterway in Hastings County",
    "industries": [
      "Government",
      "Aerospace",
      "Food processing",
      "Manufacturing",
      "Logistics"
    ],
    "areas": [
      "Trenton",
      "Frankford",
      "Batawa",
      "Bayside",
      "Wooler",
      "Glen Miller"
    ],
    "fact": "home to 8 Wing/CFB Trenton, the largest employer in the Bay of Quinte Region",
    "lat": 44.1834,
    "lng": -77.5667
  },
  {
    "slug": "st-thomas",
    "name": "St. Thomas",
    "province": "ontario",
    "population": "43,000",
    "descriptor": "a growing city in Elgin County, south of London",
    "industries": [
      "Automotive",
      "Manufacturing",
      "Healthcare",
      "Retail",
      "Tourism"
    ],
    "areas": [
      "Downtown St. Thomas",
      "Lake Margaret",
      "Shaw Valley",
      "Lyndale"
    ],
    "fact": "the site of Volkswagen's $7-billion electric vehicle battery plant",
    "lat": 42.7787,
    "lng": -81.1758
  },
  {
    "slug": "innisfil",
    "name": "Innisfil",
    "province": "ontario",
    "population": "43,000",
    "descriptor": "a fast-growing town on the western shore of Lake Simcoe, south of Barrie",
    "industries": [
      "Manufacturing",
      "Healthcare",
      "Technology",
      "Tourism",
      "Agriculture"
    ],
    "areas": [
      "Alcona",
      "Cookstown",
      "Lefroy",
      "Stroud",
      "Sandy Cove"
    ],
    "fact": "home to more than 4,000 businesses and the Friday Harbour resort on Lake Simcoe",
    "lat": 44.3001,
    "lng": -79.6114
  },
  {
    "slug": "timmins",
    "name": "Timmins",
    "province": "ontario",
    "population": "41,000",
    "descriptor": "a mining city and regional service centre in northeastern Ontario",
    "industries": [
      "Mining",
      "Healthcare",
      "Retail",
      "Government",
      "Education"
    ],
    "areas": [
      "Schumacher",
      "South Porcupine",
      "Porcupine",
      "Mountjoy",
      "Connaught",
      "Kamiskotia"
    ],
    "fact": "a regional centre for the James Bay basin, providing health, education, culture and business services",
    "lat": 48.4758,
    "lng": -81.3305
  },
  {
    "slug": "lakeshore",
    "name": "Lakeshore",
    "province": "ontario",
    "population": "40,000",
    "descriptor": "a lakefront town on Lake St. Clair, east of Windsor in Essex County",
    "industries": [
      "Automotive",
      "Manufacturing",
      "Agriculture",
      "Energy"
    ],
    "areas": [
      "Belle River",
      "Emeryville",
      "Stoney Point",
      "Comber",
      "Woodslee",
      "Puce"
    ],
    "fact": "the largest and most populous municipality in Essex County",
    "lat": 42.2399,
    "lng": -82.6511
  },
  {
    "slug": "brant",
    "name": "Brant",
    "province": "ontario",
    "population": "39,000",
    "descriptor": "a largely rural county surrounding Brantford, centred on the town of Paris",
    "industries": [
      "Manufacturing",
      "Logistics",
      "Agriculture",
      "Tourism"
    ],
    "areas": [
      "Paris",
      "St. George",
      "Burford",
      "Glen Morris",
      "Scotland",
      "Cainsville"
    ],
    "fact": "home to Tigercat Industries' expanding Paris operations and a planned Amazon delivery station",
    "lat": 43.1937,
    "lng": -80.3842
  },
  {
    "slug": "bradford-west-gwillimbury",
    "name": "Bradford West Gwillimbury",
    "province": "ontario",
    "population": "43,000",
    "descriptor": "a fast-growing town on the Holland River in southern Simcoe County",
    "industries": [
      "Agriculture",
      "Agri-food",
      "Construction",
      "Retail",
      "Manufacturing"
    ],
    "areas": [
      "Bradford",
      "Bond Head",
      "Coulson's Hill",
      "Newton Robinson",
      "Pinkerton",
      "Green Valley"
    ],
    "fact": "home to part of the Holland Marsh, a major producer of carrots, onions and salad greens",
    "lat": 44.1146,
    "lng": -79.563
  },
  {
    "slug": "new-tecumseth",
    "name": "New Tecumseth",
    "province": "ontario",
    "population": "44,000",
    "descriptor": "a fast-growing Simcoe County town made up of Alliston, Beeton and Tottenham",
    "industries": [
      "Automotive",
      "Manufacturing",
      "Agriculture",
      "Logistics"
    ],
    "areas": [
      "Alliston",
      "Beeton",
      "Tottenham",
      "Penville"
    ],
    "fact": "home to Honda's Alliston plant, which builds the Honda Civic and CR-V",
    "lat": 44.153,
    "lng": -79.8686
  },
  {
    "slug": "norfolk-county",
    "name": "Norfolk County",
    "province": "ontario",
    "population": "67,000",
    "descriptor": "a rural county on the north shore of Lake Erie, centred on the town of Simcoe",
    "industries": [
      "Agriculture",
      "Manufacturing",
      "Tourism",
      "Agri-food",
      "Hospitality"
    ],
    "areas": [
      "Simcoe",
      "Port Dover",
      "Delhi",
      "Waterford",
      "Port Rowan",
      "Turkey Point"
    ],
    "fact": "home to more Ontario farms reporting over $2 million in income than anywhere else in the province",
    "lat": 42.8371,
    "lng": -80.304
  },
  {
    "slug": "haldimand-county",
    "name": "Haldimand County",
    "province": "ontario",
    "population": "49,000",
    "descriptor": "a rural county on the north shore of Lake Erie, south of Hamilton",
    "industries": [
      "Manufacturing",
      "Energy",
      "Agriculture",
      "Construction",
      "Logistics"
    ],
    "areas": [
      "Caledonia",
      "Dunnville",
      "Hagersville",
      "Cayuga",
      "Jarvis",
      "Nanticoke"
    ],
    "fact": "home to Stelco's Lake Erie Works and Imperial's Nanticoke refinery",
    "lat": 43.0731,
    "lng": -79.9534
  },
  {
    "slug": "orillia",
    "name": "Orillia",
    "province": "ontario",
    "population": "33,000",
    "descriptor": "a lakeside city between Lake Simcoe and Lake Couchiching in Simcoe County",
    "industries": [
      "Healthcare",
      "Government",
      "Education",
      "Tourism",
      "Retail"
    ],
    "areas": [
      "Downtown Orillia",
      "West Ridge",
      "North Ward",
      "South Ward"
    ],
    "fact": "home to Soldiers' Memorial Hospital and the OPP General Headquarters, its most significant employers",
    "lat": 44.6082,
    "lng": -79.4196
  },
  {
    "slug": "fort-erie",
    "name": "Fort Erie",
    "province": "ontario",
    "population": "33,000",
    "descriptor": "a border town in Niagara Region across the Peace Bridge from Buffalo",
    "industries": [
      "Manufacturing",
      "Tourism",
      "Retail",
      "Logistics",
      "Technology"
    ],
    "areas": [
      "Crystal Beach",
      "Ridgeway",
      "Stevensville",
      "Bridgeburg",
      "Crescent Park",
      "Black Creek"
    ],
    "fact": "home to the historic Fort Erie Race Track and a new $100 million Siltech manufacturing plant",
    "lat": 42.9018,
    "lng": -78.9722
  },
  {
    "slug": "stratford",
    "name": "Stratford",
    "province": "ontario",
    "population": "33,000",
    "descriptor": "a small city on the Avon River in southwestern Ontario",
    "industries": [
      "Tourism",
      "Manufacturing",
      "Automotive",
      "Hospitality",
      "Retail"
    ],
    "areas": [
      "Downtown Stratford",
      "Avon West",
      "Romeo",
      "Hamlet",
      "Falstaff"
    ],
    "fact": "home to the Stratford Festival, which drew 430,000 attendees in 2024, and a large auto-parts base",
    "lat": 43.37,
    "lng": -80.9822
  },
  {
    "slug": "orangeville",
    "name": "Orangeville",
    "province": "ontario",
    "population": "30,000",
    "descriptor": "the commercial and administrative hub of Dufferin County",
    "industries": [
      "Manufacturing",
      "Retail",
      "Healthcare",
      "Professional services",
      "Construction"
    ],
    "areas": [
      "Downtown Orangeville",
      "Montgomery Village",
      "Credit Meadows",
      "Rolling Hills"
    ],
    "fact": "home to Headwaters Health Care Centre, with over 700 staff, and a plastics and rubber manufacturing base",
    "lat": 43.92,
    "lng": -80.0943
  },
  {
    "slug": "east-gwillimbury",
    "name": "East Gwillimbury",
    "province": "ontario",
    "population": "35,000",
    "descriptor": "a fast-growing town in northern York Region",
    "industries": [
      "Logistics",
      "Construction",
      "Retail",
      "Manufacturing",
      "Agriculture"
    ],
    "areas": [
      "Holland Landing",
      "Sharon",
      "Queensville",
      "Mount Albert",
      "River Drive Park"
    ],
    "fact": "home to a new 1.2-million-square-foot Loblaw distribution centre expected to bring over 1,000 jobs",
    "lat": 44.1,
    "lng": -79.44
  },
  {
    "slug": "sarnia",
    "name": "Sarnia",
    "province": "ontario",
    "population": "72,000",
    "descriptor": "the largest city on Lake Huron, in Lambton County",
    "industries": [
      "Energy",
      "Manufacturing",
      "Healthcare",
      "Education",
      "Agri-food"
    ],
    "areas": [
      "Downtown Sarnia",
      "Brights Grove",
      "Blackwell",
      "Mitton Village"
    ],
    "fact": "the centre of Canada's Chemical Valley, with NOVA Chemicals and Imperial among its largest employers",
    "lat": 42.9745,
    "lng": -82.4066
  },
  {
    "slug": "lasalle",
    "name": "LaSalle",
    "province": "ontario",
    "population": "33,000",
    "descriptor": "a growing town on the Detroit River south of Windsor in Essex County",
    "industries": [
      "Retail",
      "Construction",
      "Hospitality",
      "Real estate"
    ],
    "areas": [
      "Petite Côte",
      "Front Road",
      "Malden Road",
      "Sandwich West"
    ],
    "fact": "home to the 200-acre Vollmer Complex and a 60-acre Detroit River waterfront the town is redeveloping",
    "lat": 42.2167,
    "lng": -83.05
  },
  {
    "slug": "centre-wellington",
    "name": "Centre Wellington",
    "province": "ontario",
    "population": "31,000",
    "descriptor": "a Wellington County township made up of Fergus, Elora and rural hamlets",
    "industries": [
      "Manufacturing",
      "Tourism",
      "Agriculture",
      "Automotive",
      "Healthcare"
    ],
    "areas": [
      "Fergus",
      "Elora",
      "Salem",
      "Belwood",
      "Ennotville"
    ],
    "fact": "home to Elora, which draws hundreds of thousands of visitors a year, and Fergus manufacturers",
    "lat": 43.7067,
    "lng": -80.377
  },
  {
    "slug": "sherwood-park",
    "name": "Sherwood Park",
    "province": "alberta",
    "population": "99,000",
    "descriptor": "the urban centre of Strathcona County, just east of Edmonton",
    "industries": [
      "Energy",
      "Manufacturing",
      "Transportation",
      "Construction",
      "Retail"
    ],
    "areas": [
      "Ardrossan",
      "Josephburg",
      "South Cooking Lake",
      "Antler Lake"
    ],
    "fact": "the urban heart of Strathcona County, Canada's largest hydrocarbon refining cluster",
    "lat": 53.5413,
    "lng": -113.2958
  },
  {
    "slug": "fort-mcmurray",
    "name": "Fort McMurray",
    "province": "alberta",
    "population": "72,000",
    "descriptor": "the urban centre of Alberta's Regional Municipality of Wood Buffalo",
    "industries": [
      "Energy",
      "Mining",
      "Construction",
      "Transportation",
      "Retail"
    ],
    "areas": [
      "Timberlea",
      "Thickwood",
      "Abasand",
      "Downtown Fort McMurray",
      "Anzac",
      "Fort Chipewyan"
    ],
    "fact": "home to the Athabasca Oil Sands, Canada's largest oil sands deposits",
    "lat": 56.7268,
    "lng": -111.379
  },
  {
    "slug": "spruce-grove",
    "name": "Spruce Grove",
    "province": "alberta",
    "population": "38,000",
    "descriptor": "a fast-growing city just west of Edmonton on the Yellowhead Highway",
    "industries": [
      "Retail",
      "Construction",
      "Real estate",
      "Logistics",
      "Hospitality"
    ],
    "areas": [
      "Greenbury",
      "Harvest Ridge",
      "Hilldowns",
      "Jesperdale",
      "Tonewood",
      "Stoneshire"
    ],
    "fact": "a retail hub serving a primary trading area of about 70,000 people west of Edmonton",
    "lat": 53.545,
    "lng": -113.9008
  },
  {
    "slug": "leduc",
    "name": "Leduc",
    "province": "alberta",
    "population": "34,000",
    "descriptor": "a growing city south of Edmonton beside Edmonton International Airport",
    "industries": [
      "Manufacturing",
      "Logistics",
      "Retail",
      "Transportation",
      "Energy"
    ],
    "areas": [
      "Southfork",
      "Meadowview Park",
      "Linsford Park",
      "Bridgeport",
      "Windrose",
      "Tribute"
    ],
    "fact": "home to Leduc Business Park, where over 500 companies employ more than 15,000 workers",
    "lat": 53.2594,
    "lng": -113.5492
  },
  {
    "slug": "okotoks",
    "name": "Okotoks",
    "province": "alberta",
    "population": "30,000",
    "descriptor": "a town about 15 kilometres south of Calgary in the Foothills region",
    "industries": [
      "Retail",
      "Construction",
      "Manufacturing",
      "Professional services"
    ],
    "areas": [
      "Downtown Okotoks",
      "Westmount",
      "Cimarron",
      "Crystal Shores",
      "Drake Landing",
      "D'Arcy"
    ],
    "fact": "a small-business town where 96 per cent of firms have fewer than 50 employees",
    "lat": 50.7254,
    "lng": -113.9749
  },
  {
    "slug": "cochrane",
    "name": "Cochrane",
    "province": "alberta",
    "population": "32,000",
    "descriptor": "a fast-growing town on the Bow River west of Calgary",
    "industries": [
      "Construction",
      "Retail",
      "Forestry",
      "Real estate",
      "Tourism"
    ],
    "areas": [
      "Fireside",
      "GlenEagles",
      "Heritage Hills",
      "Riverview",
      "Sunset Ridge"
    ],
    "fact": "the fastest-growing Alberta community of 5,000-plus people between 2016 and 2021",
    "lat": 51.189,
    "lng": -114.467
  },
  {
    "slug": "terrebonne",
    "name": "Terrebonne",
    "province": "quebec",
    "population": "120,000",
    "descriptor": "the largest city on Montreal's North Shore, in the MRC Les Moulins",
    "industries": [
      "Healthcare",
      "Education",
      "Construction",
      "Retail",
      "Real estate",
      "Tourism"
    ],
    "areas": [
      "Vieux-Terrebonne",
      "Lachenaie",
      "La Plaine",
      "Terrebonne-Ouest",
      "Urbanova"
    ],
    "fact": "home to Hôpital Pierre-Le Gardeur, a regional CEGEP campus and three university campuses",
    "lat": 45.7,
    "lng": -73.647
  },
  {
    "slug": "saint-jean-sur-richelieu",
    "name": "Saint-Jean-sur-Richelieu",
    "province": "quebec",
    "population": "98,000",
    "descriptor": "a city on the Richelieu River in the Montérégie region south of Montreal",
    "industries": [
      "Manufacturing",
      "Government",
      "Education",
      "Tourism",
      "Retail",
      "Agriculture"
    ],
    "areas": [
      "Saint-Jean",
      "Iberville",
      "Saint-Luc",
      "L'Acadie",
      "Saint-Athanase"
    ],
    "fact": "home to the Saint-Jean Garrison, where more than 7,000 people start their military careers each year",
    "lat": 45.3071,
    "lng": -73.2627
  },
  {
    "slug": "repentigny",
    "name": "Repentigny",
    "province": "quebec",
    "population": "86,000",
    "descriptor": "a densely built suburban city on the St. Lawrence in the Lanaudière region",
    "industries": [
      "Retail",
      "Real estate",
      "Construction",
      "Healthcare",
      "Manufacturing"
    ],
    "areas": [
      "Le Gardeur",
      "Centre-ville",
      "Saint-Paul-l'Ermite",
      "Notre-Dame-des-Champs"
    ],
    "fact": "home to Galeries Rive Nord, a 115-store shopping centre that draws 5.0 million visitors a year",
    "lat": 45.7422,
    "lng": -73.45
  },
  {
    "slug": "brossard",
    "name": "Brossard",
    "province": "quebec",
    "population": "92,000",
    "descriptor": "a fast-growing South Shore city across the St. Lawrence from Montreal",
    "industries": [
      "Retail",
      "Hospitality",
      "Real estate",
      "Construction",
      "Professional services",
      "Transportation"
    ],
    "areas": [
      "Quartier DIX30",
      "Solar Uniquartier",
      "Secteur C",
      "Secteur L",
      "Secteur R"
    ],
    "fact": "home to Quartier DIX30, a lifestyle centre that receives more than 20 million visitors a year",
    "lat": 45.45,
    "lng": -73.45
  },
  {
    "slug": "drummondville",
    "name": "Drummondville",
    "province": "quebec",
    "population": "79,000",
    "descriptor": "the largest city in Centre-du-Québec, between Montreal and Quebec City",
    "industries": [
      "Manufacturing",
      "Construction",
      "Retail",
      "Food processing",
      "Logistics",
      "Tourism"
    ],
    "areas": [
      "Saint-Charles-de-Drummond",
      "Saint-Nicéphore",
      "Saint-Joachim-de-Courval",
      "Drummondville-Sud",
      "Centre-ville"
    ],
    "fact": "home to 670 manufacturing companies",
    "lat": 45.8833,
    "lng": -72.4833
  },
  {
    "slug": "saint-jerome",
    "name": "Saint-Jérôme",
    "province": "quebec",
    "population": "80,000",
    "descriptor": "the regional seat of the Laurentides, north of Montreal",
    "industries": [
      "Healthcare",
      "Manufacturing",
      "Transportation",
      "Retail",
      "Construction",
      "Government"
    ],
    "areas": [
      "Bellefeuille",
      "Lafontaine",
      "Saint-Antoine",
      "Centre-ville",
      "Quartier d'innovation industrielle"
    ],
    "fact": "home to Hôpital régional de Saint-Jérôme and a 3-million-square-foot industrial innovation park",
    "lat": 45.78,
    "lng": -74.0036
  },
  {
    "slug": "granby",
    "name": "Granby",
    "province": "quebec",
    "population": "69,000",
    "descriptor": "the main city of the Haute-Yamaska region in Quebec's Eastern Townships",
    "industries": [
      "Manufacturing",
      "Aerospace",
      "Food processing",
      "Tourism",
      "Retail",
      "Healthcare"
    ],
    "areas": [
      "Centre-ville",
      "Lac Boivin",
      "Canton de Granby",
      "Parc industriel"
    ],
    "fact": "home to 247 manufacturing companies, more than 160 of them in its industrial park",
    "lat": 45.4,
    "lng": -72.7333
  },
  {
    "slug": "blainville",
    "name": "Blainville",
    "province": "quebec",
    "population": "60,000",
    "descriptor": "a suburban city on Montreal's North Shore in the MRC Thérèse-De Blainville",
    "industries": [
      "Retail",
      "Manufacturing",
      "Life sciences",
      "Agriculture",
      "Construction"
    ],
    "areas": [
      "Fontainebleau",
      "Chambéry",
      "Plan Bouchard",
      "Côte Saint-Louis"
    ],
    "fact": "home to more than 800 businesses and industries, including the 70 most important in its MRC",
    "lat": 45.67,
    "lng": -73.88
  },
  {
    "slug": "saint-hyacinthe",
    "name": "Saint-Hyacinthe",
    "province": "quebec",
    "population": "57,000",
    "descriptor": "a Montérégie city known as Quebec's agri-food technopole",
    "industries": [
      "Agri-food",
      "Food processing",
      "Agriculture",
      "Education",
      "Manufacturing",
      "Life sciences"
    ],
    "areas": [
      "Centre-ville",
      "Saint-Thomas-d'Aquin",
      "Sainte-Rosalie",
      "Notre-Dame-de-Saint-Hyacinthe",
      "Saint-Hyacinthe-le-Confesseur",
      "La Providence"
    ],
    "fact": "home to the Université de Montréal's Faculty of Veterinary Medicine and an agri-food park of 62 industries",
    "lat": 45.63,
    "lng": -72.957
  },
  {
    "slug": "mirabel",
    "name": "Mirabel",
    "province": "quebec",
    "population": "61,000",
    "descriptor": "one of Quebec's fastest-growing cities, north of Montreal in the Laurentians",
    "industries": [
      "Aerospace",
      "Manufacturing",
      "Agriculture",
      "Construction",
      "Logistics",
      "Retail"
    ],
    "areas": [
      "Saint-Janvier",
      "Saint-Augustin",
      "Sainte-Scholastique",
      "Saint-Canut",
      "Domaine-Vert Nord",
      "Mirabel-en-Haut"
    ],
    "fact": "home to the Airbus A220 final assembly lines, where close to 4,000 people work",
    "lat": 45.65,
    "lng": -74.0833
  },
  {
    "slug": "shawinigan",
    "name": "Shawinigan",
    "province": "quebec",
    "population": "50,000",
    "descriptor": "a Mauricie city on the Saint-Maurice River with a hydroelectric heritage",
    "industries": [
      "Manufacturing",
      "Energy",
      "Tourism",
      "Healthcare",
      "Retail",
      "Technology"
    ],
    "areas": [
      "Grand-Mère",
      "Shawinigan-Sud",
      "Saint-Georges-de-Champlain",
      "Lac-à-la-Tortue",
      "Saint-Gérard-des-Laurentides",
      "Saint-Jean-des-Piles"
    ],
    "fact": "home to Shawinigan Aluminium's cast house and the gateway to La Mauricie National Park",
    "lat": 46.5667,
    "lng": -72.75
  },
  {
    "slug": "dollard-des-ormeaux",
    "name": "Dollard-des-Ormeaux",
    "province": "quebec",
    "population": "48,000",
    "descriptor": "a bilingual suburb in Montreal's West Island",
    "industries": [
      "Retail",
      "Hospitality",
      "Healthcare",
      "Real estate",
      "Professional services"
    ],
    "areas": [
      "Sunnybrooke",
      "Westpark",
      "St-Jean Sector",
      "Sunnydale"
    ],
    "fact": "home to Galeries des Sources, a 361,440-square-foot shopping centre with an IMAX cinema",
    "lat": 45.4833,
    "lng": -73.8167
  },
  {
    "slug": "rimouski",
    "name": "Rimouski",
    "province": "quebec",
    "population": "49,000",
    "descriptor": "the regional centre of Quebec's Bas-Saint-Laurent on the St. Lawrence estuary",
    "industries": [
      "Healthcare",
      "Education",
      "Technology",
      "Government",
      "Retail"
    ],
    "areas": [
      "Pointe-au-Père",
      "Le Bic",
      "Sainte-Odile-sur-Rimouski",
      "Rimouski-Est",
      "Sainte-Blandine"
    ],
    "fact": "home to ISMER-UQAR, North America's foremost French-language marine sciences research institute",
    "lat": 48.4489,
    "lng": -68.5236
  },
  {
    "slug": "chateauguay",
    "name": "Châteauguay",
    "province": "quebec",
    "population": "51,000",
    "descriptor": "a growing South Shore city at the mouth of the Châteauguay River near Montreal",
    "industries": [
      "Healthcare",
      "Manufacturing",
      "Logistics",
      "Retail",
      "Real estate"
    ],
    "areas": [
      "Châteauguay-Centre",
      "Châteauguay Heights",
      "Île Saint-Bernard",
      "Woodlands"
    ],
    "fact": "home to Hôpital Anna-Laberge and a Highway 30 industrial park drawing over $90 million in new projects",
    "lat": 45.38,
    "lng": -73.75
  },
  {
    "slug": "mascouche",
    "name": "Mascouche",
    "province": "quebec",
    "population": "51,000",
    "descriptor": "a fast-growing suburb on Montreal's North Shore in the Lanaudière region",
    "industries": [
      "Manufacturing",
      "Logistics",
      "Retail",
      "Construction",
      "Real estate"
    ],
    "areas": [
      "Mascouche Heights",
      "Du Coteau",
      "Des Hauts-Bois",
      "Du Manoir",
      "Le Gardeur"
    ],
    "fact": "home to CentrOparc, a business district with $300 million in investment on the former Mascouche airport site",
    "lat": 45.75,
    "lng": -73.6
  },
  {
    "slug": "victoriaville",
    "name": "Victoriaville",
    "province": "quebec",
    "population": "48,000",
    "descriptor": "the main city of Quebec's Centre-du-Québec Bois-Francs region",
    "industries": [
      "Manufacturing",
      "Food processing",
      "Education",
      "Agri-food",
      "Retail"
    ],
    "areas": [
      "Arthabaska",
      "Vieil-Arthabaska",
      "Sainte-Victoire-d'Arthabaska",
      "Centre-ville de Victoriaville"
    ],
    "fact": "home to a prominent Lactantia dairy factory and the Cégep de Victoriaville",
    "lat": 46.05,
    "lng": -71.9667
  },
  {
    "slug": "rouyn-noranda",
    "name": "Rouyn-Noranda",
    "province": "quebec",
    "population": "42,000",
    "descriptor": "the mining and service capital of Quebec's Abitibi-Témiscamingue region",
    "industries": [
      "Mining",
      "Manufacturing",
      "Education",
      "Healthcare",
      "Forestry",
      "Retail"
    ],
    "areas": [
      "Noranda",
      "Évain",
      "Cadillac",
      "Arntfield",
      "Mont-Brun",
      "McWatters"
    ],
    "fact": "home to the Horne Smelter, Canada's only copper smelter, and the main UQAT campus",
    "lat": 48.2366,
    "lng": -79.023
  },
  {
    "slug": "saint-eustache",
    "name": "Saint-Eustache",
    "province": "quebec",
    "population": "45,000",
    "descriptor": "an off-island suburb northwest of Montreal on the Rivière du Chêne",
    "industries": [
      "Manufacturing",
      "Automotive",
      "Transportation",
      "Retail",
      "Food processing"
    ],
    "areas": [
      "Vieux-Saint-Eustache",
      "Rivière-Nord",
      "Clair Matin",
      "Plateau des Chênes",
      "La Seigneurie"
    ],
    "fact": "home to Nova Bus headquarters and an industrial hub of 280 businesses and over 5,000 jobs",
    "lat": 45.565,
    "lng": -73.905
  },
  {
    "slug": "salaberry-de-valleyfield",
    "name": "Salaberry-de-Valleyfield",
    "province": "quebec",
    "population": "43,000",
    "descriptor": "an industrial city on the St. Lawrence River southwest of Montreal",
    "industries": [
      "Manufacturing",
      "Logistics",
      "Food processing",
      "Energy",
      "Transportation",
      "Retail"
    ],
    "areas": [
      "Grande-Île",
      "Saint-Timothée",
      "Nitro",
      "Champlain",
      "La Baie",
      "Georges-Leduc"
    ],
    "fact": "home to CEZinc, the largest primary zinc processing facility in eastern North America",
    "lat": 45.25,
    "lng": -74.13
  },
  {
    "slug": "boucherville",
    "name": "Boucherville",
    "province": "quebec",
    "population": "42,000",
    "descriptor": "an established South Shore suburb of Montreal on the St. Lawrence River",
    "industries": [
      "Manufacturing",
      "Logistics",
      "Transportation",
      "Retail",
      "Professional services",
      "Tourism"
    ],
    "areas": [
      "Vieux-Boucherville",
      "Quartier Harmonie",
      "Îles-de-Boucherville",
      "Parc industriel de Boucherville"
    ],
    "fact": "home to one of Quebec's largest industrial parks, with 664 companies and more than 24,000 jobs",
    "lat": 45.6,
    "lng": -73.45
  },
  {
    "slug": "vaudreuil-dorion",
    "name": "Vaudreuil-Dorion",
    "province": "quebec",
    "population": "43,000",
    "descriptor": "a fast-growing off-island suburb west of Montreal in Vaudreuil-Soulanges",
    "industries": [
      "Retail",
      "Manufacturing",
      "Healthcare",
      "Logistics",
      "Construction",
      "Technology"
    ],
    "areas": [
      "Dorion",
      "Vaudreuil",
      "Secteur de la Gare",
      "Chemin Dumberry",
      "Boulevard Harwood"
    ],
    "fact": "the site of the new 404-bed Vaudreuil-Soulanges hospital and eight industrial parks",
    "lat": 45.4,
    "lng": -74.0333
  },
  {
    "slug": "sorel-tracy",
    "name": "Sorel-Tracy",
    "province": "quebec",
    "population": "35,000",
    "descriptor": "an industrial city where the Richelieu River meets the St. Lawrence",
    "industries": [
      "Manufacturing",
      "Mining",
      "Education",
      "Healthcare",
      "Retail"
    ],
    "areas": [
      "Sorel",
      "Tracy",
      "Saint-Pierre-de-Sorel",
      "Vieux-Sorel"
    ],
    "fact": "home to Rio Tinto Fer et Titane's metallurgical complex, which employs 1,800 people",
    "lat": 46.0333,
    "lng": -73.1167
  },
  {
    "slug": "cote-saint-luc",
    "name": "Côte-Saint-Luc",
    "province": "quebec",
    "population": "35,000",
    "descriptor": "a mostly residential enclave city on the Island of Montreal",
    "industries": [
      "Retail",
      "Healthcare",
      "Real estate",
      "Professional services",
      "Transportation"
    ],
    "areas": [
      "Quartier Cavendish",
      "Kildare",
      "Westminster",
      "Merton",
      "Mackle"
    ],
    "fact": "planning the redevelopment of its Quartier Cavendish, CSL Shopping Centre and Décarie Square sites",
    "lat": 45.465,
    "lng": -73.665
  },
  {
    "slug": "pointe-claire",
    "name": "Pointe-Claire",
    "province": "quebec",
    "population": "33,000",
    "descriptor": "a West Island city on Lac Saint-Louis in the Montreal agglomeration",
    "industries": [
      "Retail",
      "Life sciences",
      "Technology",
      "Manufacturing",
      "Real estate",
      "Hospitality"
    ],
    "areas": [
      "Pointe-Claire Village",
      "Valois",
      "Cedar Park Heights",
      "Lakeside",
      "Northview",
      "Seignory"
    ],
    "fact": "home to Fairview Pointe-Claire, the largest shopping mall in the West Island",
    "lat": 45.45,
    "lng": -73.8167
  },
  {
    "slug": "val-dor",
    "name": "Val-d'Or",
    "province": "quebec",
    "population": "33,000",
    "descriptor": "a gold-mining city and regional service centre in Abitibi-Témiscamingue",
    "industries": [
      "Mining",
      "Forestry",
      "Manufacturing",
      "Healthcare",
      "Education",
      "Transportation"
    ],
    "areas": [
      "Sullivan",
      "Dubuisson",
      "Vassan",
      "Val-Senneville"
    ],
    "fact": "home to Eldorado Gold's Lamaque Complex and an industrial park of more than 175 companies",
    "lat": 48.1,
    "lng": -77.7833
  },
  {
    "slug": "alma",
    "name": "Alma",
    "province": "quebec",
    "population": "30,000",
    "descriptor": "a regional service centre at the head of the Saguenay River on Lac Saint-Jean",
    "industries": [
      "Manufacturing",
      "Energy",
      "Forestry",
      "Retail",
      "Education",
      "Tourism"
    ],
    "areas": [
      "Isle-Maligne",
      "Naudville",
      "Riverbend",
      "Delisle"
    ],
    "fact": "home to Rio Tinto's Alma aluminium smelter, with a capacity of 480,000 tonnes a year",
    "lat": 48.55,
    "lng": -71.65
  },
  {
    "slug": "chambly",
    "name": "Chambly",
    "province": "quebec",
    "population": "31,000",
    "descriptor": "a growing South Shore city on the Richelieu River southeast of Montreal",
    "industries": [
      "Manufacturing",
      "Tourism",
      "Retail",
      "Life sciences",
      "Hospitality"
    ],
    "areas": [
      "Vieux-Chambly",
      "Fort-Chambly",
      "Bassin-de-Chambly",
      "Grandes-Terres",
      "Petite-Rivière"
    ],
    "fact": "home to Fort Chambly and the Chambly Canal, which draws more than 250,000 visitors and cyclists a year",
    "lat": 45.45,
    "lng": -73.2833
  },
  {
    "slug": "sainte-julie",
    "name": "Sainte-Julie",
    "province": "quebec",
    "population": "30,000",
    "descriptor": "a South Shore suburb on Highway 20 east of Montreal",
    "industries": [
      "Manufacturing",
      "Retail",
      "Professional services",
      "Real estate",
      "Construction"
    ],
    "areas": [
      "Vieux-Village",
      "Domaine des Hauts-Bois",
      "Arc-en-Ciel",
      "De la Montagne"
    ],
    "fact": "planning a one-million-square-foot commercial development fronting Highway 20",
    "lat": 45.5833,
    "lng": -73.3333
  },
  {
    "slug": "saint-georges",
    "name": "Saint-Georges",
    "province": "quebec",
    "population": "33,000",
    "descriptor": "the main city of the Beauce region on the Chaudière River",
    "industries": [
      "Manufacturing",
      "Construction",
      "Transportation",
      "Education",
      "Retail"
    ],
    "areas": [
      "Saint-Georges-Ouest",
      "Saint-Georges-Est",
      "Aubert-Gallion",
      "Saint-Jean-de-la-Lande"
    ],
    "fact": "home to the headquarters of Manac, Canada's biggest trailer manufacturer, and Canam Group",
    "lat": 46.1167,
    "lng": -70.6667
  },
  {
    "slug": "prince-albert",
    "name": "Prince Albert",
    "province": "saskatchewan",
    "population": "38,000",
    "descriptor": "the third-largest city in Saskatchewan and a gateway to the north",
    "industries": [
      "Healthcare",
      "Government",
      "Retail",
      "Forestry",
      "Construction",
      "Tourism"
    ],
    "areas": [
      "East Flat",
      "West Flat",
      "Midtown",
      "Crescent Heights",
      "River Heights"
    ],
    "fact": "home to Victoria Hospital, where an $898 million acute care tower is being built",
    "lat": 53.2033,
    "lng": -105.7531
  },
  {
    "slug": "moose-jaw",
    "name": "Moose Jaw",
    "province": "saskatchewan",
    "population": "34,000",
    "descriptor": "the fourth-largest city in Saskatchewan, west of Regina",
    "industries": [
      "Agri-food",
      "Agriculture",
      "Government",
      "Mining",
      "Transportation",
      "Tourism"
    ],
    "areas": [
      "Palliser",
      "Hillcrest",
      "Sunningdale",
      "Westmount",
      "Elsom"
    ],
    "fact": "home to 15 Wing Moose Jaw, the city's largest employer, and a cluster of agri-food processors",
    "lat": 50.3934,
    "lng": -105.5519
  },
  {
    "slug": "saanich",
    "name": "Saanich",
    "province": "british-columbia",
    "population": "118,000",
    "descriptor": "the most populous municipality on Vancouver Island, bordering Victoria",
    "industries": [
      "Education",
      "Technology",
      "Life sciences",
      "Healthcare",
      "Agriculture",
      "Government"
    ],
    "areas": [
      "Cadboro Bay",
      "Gordon Head",
      "Cordova Bay",
      "Royal Oak",
      "Shelbourne",
      "Tillicum"
    ],
    "fact": "home to the University of Victoria, Camosun College and the Vancouver Island Technology Park",
    "lat": 48.484,
    "lng": -123.381
  },
  {
    "slug": "delta",
    "name": "Delta",
    "province": "british-columbia",
    "population": "108,000",
    "descriptor": "a port and farming city of three communities south of Vancouver",
    "industries": [
      "Logistics",
      "Transportation",
      "Manufacturing",
      "Agriculture",
      "Construction",
      "Retail"
    ],
    "areas": [
      "Ladner",
      "Tsawwassen",
      "North Delta",
      "Tilbury",
      "Westham Island"
    ],
    "fact": "home to Deltaport, Canada's largest container shipping port",
    "lat": 49.0847,
    "lng": -123.0586
  },
  {
    "slug": "chilliwack",
    "name": "Chilliwack",
    "province": "british-columbia",
    "population": "93,000",
    "descriptor": "a fast-growing Fraser Valley city east of Abbotsford",
    "industries": [
      "Agriculture",
      "Manufacturing",
      "Construction",
      "Healthcare",
      "Education",
      "Agri-food"
    ],
    "areas": [
      "Chilliwack Proper",
      "Sardis",
      "Vedder",
      "Promontory",
      "Yarrow",
      "Rosedale"
    ],
    "fact": "home to Canada Education Park, with a University of the Fraser Valley campus",
    "lat": 49.1579,
    "lng": -121.9515
  },
  {
    "slug": "maple-ridge",
    "name": "Maple Ridge",
    "province": "british-columbia",
    "population": "91,000",
    "descriptor": "a growing city on the eastern edge of Metro Vancouver",
    "industries": [
      "Tourism",
      "Agriculture",
      "Healthcare",
      "Retail",
      "Manufacturing",
      "Construction"
    ],
    "areas": [
      "Haney",
      "Albion",
      "Hammond",
      "Whonnock",
      "Silver Valley",
      "Thornhill"
    ],
    "fact": "the main gateway to Golden Ears Provincial Park, which hosts about 600,000 visitors each year",
    "lat": 49.2194,
    "lng": -122.5984
  },
  {
    "slug": "new-westminster",
    "name": "New Westminster",
    "province": "british-columbia",
    "population": "79,000",
    "descriptor": "a dense, historic city on the Fraser River in Metro Vancouver",
    "industries": [
      "Healthcare",
      "Transportation",
      "Logistics",
      "Retail",
      "Education",
      "Government"
    ],
    "areas": [
      "Sapperton",
      "Queensborough",
      "Uptown",
      "Downtown",
      "Queen's Park",
      "West End"
    ],
    "fact": "home to Royal Columbian Hospital, the city's largest employer with 3,500 employees",
    "lat": 49.2057,
    "lng": -122.911
  },
  {
    "slug": "north-vancouver",
    "name": "North Vancouver",
    "province": "british-columbia",
    "population": "88,000",
    "descriptor": "a mountain-backed district municipality on Metro Vancouver's North Shore",
    "industries": [
      "Tourism",
      "Retail",
      "Construction",
      "Life sciences",
      "Manufacturing",
      "Professional services"
    ],
    "areas": [
      "Lynn Valley",
      "Deep Cove",
      "Edgemont",
      "Seymour",
      "Upper Capilano",
      "Canyon Heights"
    ],
    "fact": "home to the famous Capilano Suspension Bridge and a large film, tourism and recreation economy",
    "lat": 49.32,
    "lng": -123.0724
  },
  {
    "slug": "vernon",
    "name": "Vernon",
    "province": "british-columbia",
    "population": "45,000",
    "descriptor": "a growing city in British Columbia's North Okanagan",
    "industries": [
      "Healthcare",
      "Forestry",
      "Tourism",
      "Agriculture",
      "Retail",
      "Education"
    ],
    "areas": [
      "East Hill",
      "Mission Hill",
      "Harwood",
      "Okanagan Landing",
      "Bella Vista",
      "Middleton Mountain"
    ],
    "fact": "home to Kal Tire, Canada's largest independent tire dealer, and forest products maker Tolko Industries",
    "lat": 50.2671,
    "lng": -119.272
  },
  {
    "slug": "port-coquitlam",
    "name": "Port Coquitlam",
    "province": "british-columbia",
    "population": "61,000",
    "descriptor": "a suburban city in Metro Vancouver's Tri-Cities area",
    "industries": [
      "Transportation",
      "Logistics",
      "Manufacturing",
      "Food processing",
      "Retail",
      "Construction"
    ],
    "areas": [
      "Citadel Heights",
      "Mary Hill",
      "Lincoln Park",
      "Birchland Manor",
      "Oxford Heights",
      "Riverwood"
    ],
    "fact": "home to B.C.'s largest rail yard, operated by Canadian Pacific and still one of the city's top employers",
    "lat": 49.2625,
    "lng": -122.7811
  },
  {
    "slug": "west-vancouver",
    "name": "West Vancouver",
    "province": "british-columbia",
    "population": "44,000",
    "descriptor": "an affluent district municipality on Metro Vancouver's North Shore",
    "industries": [
      "Retail",
      "Real estate",
      "Healthcare",
      "Professional services",
      "Hospitality",
      "Finance"
    ],
    "areas": [
      "Ambleside",
      "Dundarave",
      "Horseshoe Bay",
      "British Properties",
      "Caulfeild",
      "Cypress Park"
    ],
    "fact": "home to Park Royal, Canada's first covered shopping mall, with 280 stores",
    "lat": 49.328,
    "lng": -123.16
  },
  {
    "slug": "mission",
    "name": "Mission",
    "province": "british-columbia",
    "population": "42,000",
    "descriptor": "a Fraser River city on the eastern edge of Metro Vancouver",
    "industries": [
      "Government",
      "Healthcare",
      "Education",
      "Construction",
      "Retail",
      "Forestry"
    ],
    "areas": [
      "Hatzic",
      "Silverdale",
      "Cedar Valley",
      "Stave Falls",
      "Steelhead",
      "Durieu"
    ],
    "fact": "home to one of the largest underdeveloped waterfronts in Western Canada, with 296 acres on the Fraser River",
    "lat": 49.1337,
    "lng": -122.3112
  },
  {
    "slug": "penticton",
    "name": "Penticton",
    "province": "british-columbia",
    "population": "37,000",
    "descriptor": "a lakeside city in British Columbia's South Okanagan",
    "industries": [
      "Tourism",
      "Agri-food",
      "Healthcare",
      "Hospitality",
      "Retail",
      "Education"
    ],
    "areas": [
      "Downtown",
      "Wiltse",
      "Columbia",
      "Skaha Lake",
      "Carmi",
      "Uplands"
    ],
    "fact": "a tourism and wine-industry hub where over 2,000 people work in tourism-related businesses",
    "lat": 49.4991,
    "lng": -119.5937
  },
  {
    "slug": "campbell-river",
    "name": "Campbell River",
    "province": "british-columbia",
    "population": "36,000",
    "descriptor": "a coastal city on northern Vancouver Island",
    "industries": [
      "Agri-food",
      "Forestry",
      "Tourism",
      "Healthcare",
      "Retail",
      "Logistics"
    ],
    "areas": [
      "Willow Point",
      "Campbellton",
      "Quinsam Heights",
      "Ocean Grove",
      "Downtown"
    ],
    "fact": "home to the headquarters of Cermaq Canada, Mowi Canada West and Grieg Seafood BC",
    "lat": 50.0244,
    "lng": -125.2475
  },
  {
    "slug": "langford",
    "name": "Langford",
    "province": "british-columbia",
    "population": "47,000",
    "descriptor": "a fast-growing city on Greater Victoria's West Shore",
    "industries": [
      "Construction",
      "Retail",
      "Technology",
      "Manufacturing",
      "Hospitality",
      "Real estate"
    ],
    "areas": [
      "Westhills",
      "Bear Mountain",
      "Happy Valley",
      "Florence Lake",
      "Mill Hill",
      "Glen Lake"
    ],
    "fact": "the fastest growing community in British Columbia in the 2021 census",
    "lat": 48.4475,
    "lng": -123.4956
  },
  {
    "slug": "port-moody",
    "name": "Port Moody",
    "province": "british-columbia",
    "population": "34,000",
    "descriptor": "a waterfront city at the head of Burrard Inlet in Metro Vancouver",
    "industries": [
      "Hospitality",
      "Food processing",
      "Retail",
      "Tourism",
      "Professional services",
      "Real estate"
    ],
    "areas": [
      "Moody Centre",
      "Heritage Mountain",
      "Glenayre",
      "Ioco",
      "College Park",
      "Inlet Centre"
    ],
    "fact": "home to Brewers Row, six award-winning breweries on a three-block stretch of Murray Street",
    "lat": 49.283,
    "lng": -122.8317
  },
  {
    "slug": "west-kelowna",
    "name": "West Kelowna",
    "province": "british-columbia",
    "population": "36,000",
    "descriptor": "a growing city on the west shore of Okanagan Lake",
    "industries": [
      "Tourism",
      "Agri-food",
      "Forestry",
      "Construction",
      "Retail",
      "Healthcare"
    ],
    "areas": [
      "Westbank Centre",
      "Glenrosa",
      "Rose Valley",
      "Lakeview Heights",
      "Shannon Lake",
      "Smith Creek"
    ],
    "fact": "home to Mission Hill Family Estate Winery and a wine trail lined with a dozen wineries",
    "lat": 49.8625,
    "lng": -119.5833
  }
];
